[package]
name = "sui_dao"
version = "1.0.0"
edition = "2024"

# Sui framework is auto-resolved in Sui CLI 1.63+
[dependencies]
sui_staking = { local = "../sui_staking" }

[addresses]
sui_dao = "0x0"

[dev-dependencies]

[dev-addresses]
